- name: get mysql rpm
  shell: sudo wget https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm
  become: true

- name: install mysql rpm
  shell: dnf install mysql80-community-release-el9-1.noarch.rpm -y
  become: true

- name: import keys for mysql
  shell: rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
  become: true

- name: 'start mysql service'
  service:
    name: mysqld
    state: started

- name: Create new db
  debug:
    msg: 'Create DB employee_db'